### NOTES ###

### Get all note metadata for current user
GET http://localhost:4000/notes
Authorization: Bearer <user-id>

### Get one note by id
GET http://localhost:4000/notes/<note-id>
Authorization: Bearer <user-id>

### Create a note for current user
POST http://localhost:4000/notes
Authorization: Bearer <user-id>
Content-Type: application/json

{
  "title": "Make SuperAjanda great again!"
}

### Update a note by id
PATCH http://localhost:4000/notes/<note-id>
Authorization: Bearer <user-id>
Content-Type: application/json

{
  "title": "<note-title>",
  "content": "<note-content>",
  "tagIds": ["<new-tag-id-1>", "<new-tag-id-2>"]
}

### Delete a note by id
DELETE http://localhost:4000/notes/<note-id>
Authorization: Bearer <user-id>


### TAGS ###

### Get all tags for current user
GET http://localhost:4000/tags/
Authorization: Bearer <user-id>

### Get one tag by id
GET http://localhost:4000/tags/<tag-id>
Authorization: Bearer <user-id>

### Create a tag attached to a note
POST http://localhost:4000/tags/
Authorization: Bearer <user-id>
Content-Type: application/json

{
  "noteId": "<note-id>",
  "name": "<tag-name>"
}

### Update a tag by id
PATCH http://localhost:4000/tags/<tag-id>
Authorization: Bearer <user-id>
Content-Type: application/json

{
  "name": "<tag-name>"
}

### Delete a tag by id
DELETE http://localhost:4000/tags/<tag-id>
Authorization: Bearer <user-id>


### USERS (not for production) ###

### Get all users
GET http://localhost:4000/users
Authorization: Bearer <user-id>

### Create a user with custom id
POST http://localhost:4000/users
Authorization: Bearer <user-id>
Content-Type: application/json

{
  "email": "<user-email>",
  "name": "<user-name>",
  "id": "<user-id>"
}

### Delete current user
DELETE http://localhost:4000/users
Authorization: Bearer <user-id>
